### ISSUE TITLE
Add Semaphore for Blockchain Transactions From the same account.

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/element#34]
An invalid nonce error will be thrown if the same account tries to write to ethereum at the same time.

We added a hacky retry in #30 

We need to consider what parallel write means for the sidetree protocol.

I think its generally invalid for the same account to try and anchor 2 different files at once.

While this happens in tests, in production each node should have a unique funded hot wallet, and this sort of thing should not be happening.

**Comment by OR13** [comment]
Let me know your thoughts.

**Comment by gjgd** [comment]
If the error happens only while testing, then we should modify our test setup, not accomodate the codebase for the tests. Three solutions come to mind:
- Add a semaphore on the web3 instance, so that only one sidetree service can access it at the time (requires all sidetree instances to use the same web3 instance)
- Sleeping a few ms after an RPC call to wait for consistency to be reached
- Use different accounts for different instances of the sidetree service. That requires having a test service that manages which funded web3 accounts are used and which are not.

**Comment by OR13** [comment]
https://ethereum.stackexchange.com/questions/39790/concurrency-patterns-for-account-nonce

We currently support Candidate 2 in element-lib.

I think its the best because all the other ones require coordination which will not always be possible.

Most recent since the contract interface used by element is very small I think its ok to add the retry loop. 

https://github.com/decentralized-identity/element/blob/development/packages/element-lib/src/adapters/blockchain/ethereum/index.js#L75
