### ISSUE TITLE
Husky logic should trigger only in element-core

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/element#54]
This logic triggers in all packages

https://github.com/decentralized-identity/element/blob/development/packages/element-core/package.json#L57-L58

**Comment by gjgd** [comment]
Husky config should be only in the top level package.json

**Comment by OR13** [comment]
The lerna publish setup we have not requires that all packages have the same commit lint, so that changelogs can be built automatically.

I think we want to the devex of core to be applied everywhere.

I'm not sure I have got the lerna setup right, but my desired outcome is:

- if you open the mono repo, you can edit files and commits are linted.
- if you open a specific package, you can edit file and commits are linted.
- there should be not lint thrashing
- lerna publish should generate change logs for all changed packages, and determine version number.

I don't know if this means that some things need to be duplicated. I do know that `.vscode` seems to need to be duplicated.

**Comment by OR13** [comment]
Seeing errors when making commits after lerna clean and lerna bootstrap.

```
› git commit -m "fix: pin truffle-hdwallet-provider to 1.0.5"
husky > pre-commit (node v10.15.3)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ✔ Running linters...
husky > commit-msg (node v10.15.3)
/Users/USER/element/node_modules/@commitlint/cli/lib/cli.js:109
	throw err;
	^

Error: ENOENT: no such file or directory, open '/Users/USER/element/packages/element-core/config/commitlint.config.js'
```

**Comment by gjgd** [comment]
You need to run `npm install` in the root directory to reinstall the git hooks.

**Comment by gjgd** [comment]
Nevermind, you need to do `npm install husky --save-dev` to reinstall git hooks
